version: '2'
services:
    recipeshop-app:
        image: recipeshop
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://recipeshop-postgresql:5432/RecipeShop
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    recipeshop-postgresql:
        extends:
            file: postgresql.yml
            service: recipeshop-postgresql
